version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: musike
      POSTGRES_USER: musike_user
      POSTGRES_PASSWORD: musike_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c listen_addresses='*' -c log_statement=all

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Backend Go API
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URL=https://localhost:3000/callback
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgres://musike_user:musike_password@postgres:5432/musike?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - PORT=3000
      - USE_HTTPS=true
    depends_on:
      - postgres
      - redis
    volumes:
      - ./certs:/app/certs:ro

  # Frontend Next.js
  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://localhost:3000

volumes:
  postgres_data:
  redis_data:
