
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: musike
      POSTGRES_USER: musike_user
      POSTGRES_PASSWORD: musike_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c listen_addresses='*' -c log_statement=all

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Backend Go API
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID:-your_spotify_client_id}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET:-your_spotify_client_secret}
      - SPOTIFY_REDIRECT_URL=http://127.0.0.1:3000/callback
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - DATABASE_URL=postgres://musike_user:musike_password@postgres:5432/musike?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - PORT=8080
      - USE_HTTPS=false
    depends_on:
      - postgres
      - redis

  # Frontend Next.js
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
